version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./images:/var/www/html/images
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - cafe-net

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cafe
      MYSQL_USER: cafe_user
      MYSQL_PASSWORD: cafe
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d
    networks:
      - cafe-net

volumes:
  db_data:

networks:
  cafe-net:

